const $=id=>document.getElementById(id);
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const STORAGE_KEY='pulselab-analog-rec-v1';

const STUDIES={
  covid:{name:'Stanford COVID smartwatch study',short:'COVID',citation:'Mishra et al. · Nature Biomedical Engineering · 2020',url:'https://doi.org/10.1038/s41551-020-00640-6'},
  digital:{name:'Stanford digital-health study',short:'INFECTION / INFLAMMATION',citation:'Li et al. · PLOS Biology · 2017',url:'https://doi.org/10.1371/journal.pbio.2001402'},
  wesad:{name:'WESAD wearable stress study',short:'STRESS',citation:'Schmidt et al. · ICMI · 2018',url:'https://doi.org/10.24432/C57K5T'}
};

const CASES=[
  {id:'AQC0L71',study:'covid',angle:-78,signals:['hr','temp','activity','sleep'],kind:'COVID-19',outcome:'Hospitalized; recovered 41 days after symptoms began',summary:'Wearable heart-rate warnings preceded clinical worsening. The participant later tested positive for COVID-19 and was hospitalized.',timeline:[['Before symptoms','Two heart-rate methods in the paper produced warnings.'],['Symptoms begin','Cough, fatigue, aches and pains were reported.'],['Over the next 22 days','Symptoms stayed mild to moderate, then worsened quickly. Temperature rose and a COVID-19 test was positive.'],['5 days later','The participant was admitted to the hospital.'],['Day 41','The participant had recovered.']],evidence:{type:'events',title:'Reported clinical timeline'}},
  {id:'APGIB2T',study:'covid',angle:-38,signals:['hr','temp','activity','sleep'],kind:'COVID-19',outcome:'18-day illness, 12-day recovery, then relapse',summary:'A resting-heart-rate warning appeared about a week before symptoms. The participant later had severe illness, temporary recovery, and relapse.',timeline:[['7 days before symptoms','An early resting-heart-rate warning appeared.'],['Symptoms begin','Severe diarrhea, fatigue, headaches and elevated temperature were reported; COVID-19 was positive.'],['First 18 days','The initial illness lasted 18 days.'],['Next 12 days','The participant felt recovered.'],['After that','Symptoms relapsed with elevated temperature, fatigue, diarrhea and new heart-rate warnings.']],evidence:{type:'events',title:'Reported clinical timeline'}},
  {id:'A1K5DRI',study:'covid',angle:2,signals:['hr','temp','activity','sleep'],kind:'COVID-19',outcome:'23-day illness',summary:'A resting-heart-rate warning appeared three days before daily symptom tracking; the reported illness period lasted 23 days.',timeline:[['3 days before symptoms','A resting-heart-rate warning appeared.'],['Symptoms begin','Daily symptom tracking started.'],['During illness','Temperature rose quickly, with severe fatigue, aches and pains.'],['Day 23','The reported illness period ended after a slow recovery.']],evidence:{type:'events',title:'Reported clinical timeline'}},
  {id:'A0VFT1N',study:'covid',angle:42,signals:['hr','activity','sleep','resp'],kind:'COVID-19',outcome:'Hospitalized for shortness of breath on day 35',summary:'A heart-rate warning preceded a 13-day COVID-19 illness. Shortness of breath later returned and the participant was hospitalized.',timeline:[['Before symptoms','A resting-heart-rate warning appeared.'],['First 13 days','COVID-19 illness was reported, followed by fatigue and occasional chest pain.'],['Later','Shortness of breath returned together with new heart-rate warnings.'],['Day 35','The participant was hospitalized for shortness of breath.']],evidence:{type:'events',title:'Reported clinical timeline'}},
  {id:'Participant #1',study:'digital',angle:82,signals:['hr','temp','spo2'],kind:'Lyme disease',outcome:'Lyme disease was later confirmed by blood test',summary:'Heart rate and skin temperature increased, oxygen saturation was unusually low, and a later Lyme antibody test was positive.',timeline:[['Day 470','Abnormally high heart rate and skin temperature appeared; SpO₂ was also unusually low.'],['Days 470–474','About 14–55% of daily heart-rate readings and 5–19% of skin-temperature readings were outliers.'],['Day 474','The participant saw a physician and received doxycycline. Symptoms and abnormal vital signs disappeared the next day.'],['Day 487','A Lyme antibody blood test was positive.']],evidence:{type:'bars',title:'Measurements reported in the paper',rows:[{label:'HR readings flagged',value:55,max:60,suffix:'% max',note:'14–55% per day'},{label:'Skin-temp readings flagged',value:19,max:60,suffix:'% max',note:'5–19% per day'},{label:'Highest oral temperature',value:102,max:105,suffix:' °F'}]}},
  {id:'Participant #59',study:'digital',angle:124,signals:['hr','temp'],kind:'Inflammatory illness',outcome:'Heart-rate change appeared 48–72 hours before symptoms',summary:'This participant had one of the clearest pre-symptom heart-rate and skin-temperature changes in the 2017 Stanford study.',timeline:[['48–72 h before symptoms','Heart rate was 3.55 standard deviations above that participant’s background.'],['48 h before symptoms','Skin temperature was 2.45 standard deviations above background.'],['Symptom day','Skin temperature was 2.15 standard deviations above background.']],evidence:{type:'bars',title:'Change from the participant’s baseline',rows:[{label:'Heart rate before symptoms',value:3.55,max:5,suffix:' SD'},{label:'Skin temp 48 h before',value:2.45,max:5,suffix:' SD'},{label:'Skin temp on symptom day',value:2.15,max:5,suffix:' SD'}]}},
  {id:'Participant #58',study:'digital',angle:164,signals:['hr'],kind:'Inflammatory illness',outcome:'Two illness days ranked among the strongest heart-rate outliers',summary:'Two illness days had unusually high heart-rate outlier scores, and the heart-rate signal tracked CRP closely.',timeline:[['Illness episode 1','The heart-rate day was 3.40 standard deviations above background.'],['Illness episode 2','A second illness day was 2.02 standard deviations above background.'],['Across blood tests','The paper reports a 0.90 correlation between CRP and the share of high heart-rate readings.']],evidence:{type:'bars',title:'Measurements reported in the paper',rows:[{label:'Illness day 1',value:3.40,max:5,suffix:' SD'},{label:'Illness day 2',value:2.02,max:5,suffix:' SD'},{label:'HR–CRP correlation',value:.90,max:1,suffix:' r'}]}},
  {id:'Participant #37',study:'digital',angle:204,signals:['hr'],kind:'Inflammatory illness',outcome:'The illness period was the strongest heart-rate outlier in 25 monitored days',summary:'The participant’s illness period produced the strongest heart-rate outlier in the reported 25-day monitoring window.',timeline:[['Illness period','The heart-rate outlier measure was 4.66 standard deviations above background.'],['Rank','It ranked #1 out of 25 monitored days for the fraction of high heart-rate readings.']],evidence:{type:'bars',title:'Measurement reported in the paper',rows:[{label:'Heart-rate outlier',value:4.66,max:5,suffix:' SD'}]}},
  {id:'S2',study:'wesad',angle:238,signals:['hr','temp','resp'],kind:'Experimentally induced stress',outcome:'Real labeled stress recording, not an illness case',summary:'This participant provides a non-infection comparison: acute experimental stress also changes multiple wearable signals.',timeline:[['Baseline','A neutral resting period was recorded.'],['Stress task','Public speaking and mental arithmetic were used to induce acute stress.'],['Other labeled period','The recording also contains an amusement condition.']],evidence:{type:'events',title:'Reported study protocol'}},
  {id:'S3',study:'wesad',angle:268,signals:['hr','temp','resp'],kind:'Experimentally induced stress',outcome:'Real labeled stress recording, not an illness case',summary:'A second WESAD participant with synchronized chest and wrist sensor recordings across labeled physiological states.',timeline:[['Baseline','Neutral physiology was recorded.'],['Stress task','The participant completed the standardized social-stress task.'],['Sensors','The dataset includes ECG/BVP, respiration, skin temperature, motion and electrodermal activity.']],evidence:{type:'events',title:'Reported study protocol'}},
  {id:'S4',study:'wesad',angle:300,signals:['hr','temp','resp'],kind:'Experimentally induced stress',outcome:'Real labeled stress recording, not an illness case',summary:'This stress-labeled participant is included because an abnormal multi-signal wearable pattern is not specific to disease.',timeline:[['Baseline','A neutral baseline period was recorded.'],['Stress task','The participant completed the same standardized stress protocol.'],['Interpretation','The study label is stress, not disease.']],evidence:{type:'events',title:'Reported study protocol'}},
  {id:'S5',study:'wesad',angle:332,signals:['hr','temp','resp'],kind:'Experimentally induced stress',outcome:'Real labeled stress recording, not an illness case',summary:'Another participant from the 15-subject WESAD dataset, included as a non-infection physiological comparison.',timeline:[['Baseline','Neutral physiology was recorded first.'],['Stress task','A standardized public-speaking and mental-math stressor followed.'],['Use here','This comparison helps separate general physiological stress from disease-specific interpretation.']],evidence:{type:'events',title:'Reported study protocol'}}
];

let selectedId=CASES[0].id,timer=null;
const view={x:0,y:0,scale:1,ready:false,drag:false,sx:0,sy:0,px:0,py:0};
const WORLD={w:1200,h:800,cx:600,cy:400};

function num(id){const el=$(id);if(!el||el.value==='')return null;const x=Number(el.value);return Number.isFinite(x)?x:null;}
function ratio(cur,base){return Number.isFinite(cur)&&Number.isFinite(base)&&Math.abs(base)>1e-9?(cur-base)/Math.abs(base):null;}
function signalLabel(key){return({hr:'resting heart rate',temp:'skin temperature',activity:'activity',sleep:'sleep',spo2:'blood oxygen',resp:'breathing rate'})[key]||key;}
function currentPattern(){
  const p={hr:ratio(num('c_resting_hr'),num('b_resting_hr')),sleep:ratio(num('c_sleep_hours'),num('b_sleep_hours')),activity:ratio(num('c_steps'),num('b_steps')),temp:Number.isFinite(num('c_temperature_c'))&&Number.isFinite(num('b_temperature_c'))?num('c_temperature_c')-num('b_temperature_c'):null,spo2:Number.isFinite(num('c_spo2'))&&Number.isFinite(num('b_spo2'))?num('b_spo2')-num('c_spo2'):null,resp:ratio(num('c_respiratory_rate'),num('b_respiratory_rate'))};
  const flags=[];if(Number.isFinite(p.hr)&&p.hr>.08)flags.push('hr');if(Number.isFinite(p.temp)&&p.temp>.35)flags.push('temp');if(Number.isFinite(p.activity)&&p.activity<-.20)flags.push('activity');if(Number.isFinite(p.sleep)&&p.sleep<-.15)flags.push('sleep');if(Number.isFinite(p.spo2)&&p.spo2>=1)flags.push('spo2');if(Number.isFinite(p.resp)&&p.resp>.12)flags.push('resp');
  const sev=[Number.isFinite(p.hr)?clamp(p.hr/.35):null,Number.isFinite(p.temp)?clamp(p.temp/1.4):null,Number.isFinite(p.activity)?clamp(-p.activity/.8):null,Number.isFinite(p.sleep)?clamp(-p.sleep/.5):null,Number.isFinite(p.spo2)?clamp(p.spo2/6):null,Number.isFinite(p.resp)?clamp(p.resp/.5):null].filter(Number.isFinite);
  return {...p,flags,severity:sev.length?sev.reduce((a,b)=>a+b,0)/sev.length:0,hasData:sev.length>=2};
}
function matchScore(c,p){if(!p.hasData)return 55;const shared=c.signals.filter(x=>p.flags.includes(x)).length;const missed=p.flags.filter(x=>!c.signals.includes(x)).length;const studyBoost=c.study==='digital'?4:c.study==='covid'?3:0;return Math.round(clamp(52+shared*9-missed*2+p.severity*12+studyBoost,48,97));}
function ranked(p){return CASES.map(c=>({...c,score:matchScore(c,p)})).sort((a,b)=>b.score-a.score);}
function position(c){const r=clamp(125+(100-c.score)*6,130,415),a=c.angle*Math.PI/180;return{x:WORLD.cx+Math.cos(a)*r,y:WORLD.cy+Math.sin(a)*r};}
function recommendation(p,top){
  if(!p.hasData)return{days:14,panel:'CBC + CMP',title:'Upload WHOOP history to compute a meaningful comparison.',body:'The participant network requires a personal baseline plus the current live measurements. Without both, node distance is not interpretable.'};
  const shared=top.signals.filter(x=>p.flags.includes(x));
  const sharedText=shared.length?shared.map(signalLabel).join(', '):'the current wearable pattern';
  if(p.severity>=.58)return{days:3,panel:'CBC + CMP',title:`Closest published comparison: ${top.id}`,body:`The current pattern and ${top.id} share directional changes in ${sharedText}. This is enough to justify reviewing the case and adding blood measurements, but it is not evidence that you have the same condition.`};
  return{days:7,panel:'CBC + CMP',title:`Nearest published comparison: ${top.id}`,body:`The current pattern shares some of the same directional changes seen in ${top.id}. The network is useful for selecting comparable study records, not for assigning a diagnosis.`};
}
function publish(rec,top){const payload={days:rec.days,panel:rec.panel,similarity:top?.score||null,synthetic:false,source:'multi-study real participant network',updatedAt:Date.now()};try{localStorage.setItem(STORAGE_KEY,JSON.stringify(payload));}catch(_){}window.dispatchEvent(new CustomEvent('pulselab:analog-recommendation',{detail:payload}));}

function shell(){
  const host=$('populationContent');if(!host||$('simplePopulation'))return;
  host.innerHTML=`<div id="simplePopulation" class="simple-population"><section class="population-summary"><div><div class="eyebrow">Nearest published comparison</div><h2 id="simpleTitle">Building the participant network…</h2><p id="simpleBody"></p></div><div class="population-summary-test"><span>Recommended additional measurement</span><strong id="simplePanel">CBC + CMP</strong><small id="simpleWindow">—</small></div></section><section class="network-layout"><div class="card network-card"><div class="network-heading"><div><div class="eyebrow">Participant network</div><h2>Similarity across three published wearable studies.</h2><p>Each node is a de-identified study participant. Position is determined by a PulseLab similarity score based on which wearable signals moved in the same direction as the current pattern. Participant outcomes and reported measurements come from the cited studies; node position and the similarity percentage are computed for this demo.</p></div><div class="network-controls"><button id="zoomOut" type="button" aria-label="Zoom out">−</button><button id="resetNetwork" type="button">Reset view</button><button id="zoomIn" type="button" aria-label="Zoom in">+</button></div></div><div id="networkLegend" class="network-legend"></div><div id="participantNetwork" class="participant-network"><div id="networkWorld" class="network-world"></div></div><div class="network-foot"><span>Drag empty space to pan</span><span>Use the wheel or controls to zoom</span><span>Select a node to inspect its source record</span></div></div><div class="card participant-detail-card"><div id="simpleCaseDetail"></div></div></section><section class="card study-library-card"><div><div class="eyebrow">Evidence represented in the network</div><h2>Illness, inflammation and experimentally induced stress.</h2><p>The comparison set intentionally includes both illness and non-illness cases. That makes the network useful for asking whether a pattern resembles previously observed physiology without pretending that wearable similarity identifies a specific disease.</p></div><div id="studyLibrary" class="study-library"></div></section></div>`;
  installPan();
}

function installPan(){
  const vp=$('participantNetwork');if(!vp||vp.dataset.panReady)return;vp.dataset.panReady='1';
  vp.addEventListener('pointerdown',e=>{if(e.target.closest('.network-node,.network-controls'))return;view.drag=true;view.sx=e.clientX;view.sy=e.clientY;view.px=view.x;view.py=view.y;vp.classList.add('dragging');vp.setPointerCapture?.(e.pointerId);});
  vp.addEventListener('pointermove',e=>{if(!view.drag)return;view.x=view.px+(e.clientX-view.sx);view.y=view.py+(e.clientY-view.sy);applyView();});
  const stop=e=>{if(!view.drag)return;view.drag=false;vp.classList.remove('dragging');try{vp.releasePointerCapture?.(e.pointerId);}catch(_){}};
  vp.addEventListener('pointerup',stop);vp.addEventListener('pointercancel',stop);
  vp.addEventListener('wheel',e=>{e.preventDefault();const rect=vp.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top,wx=(mx-view.x)/view.scale,wy=(my-view.y)/view.scale,next=clamp(view.scale*(e.deltaY<0?1.12:.89),.55,1.9);view.x=mx-wx*next;view.y=my-wy*next;view.scale=next;applyView();},{passive:false});
  $('zoomIn').addEventListener('click',()=>zoomBy(1.18));$('zoomOut').addEventListener('click',()=>zoomBy(.85));$('resetNetwork').addEventListener('click',resetView);
  window.addEventListener('resize',()=>{if(view.ready)resetView();});
}
function applyView(){const world=$('networkWorld');if(world)world.style.transform=`translate(${view.x}px,${view.y}px) scale(${view.scale})`;}
function resetView(){const vp=$('participantNetwork');if(!vp)return;const r=vp.getBoundingClientRect();view.scale=Math.min(1,Math.max(.72,r.width/900));view.x=r.width/2-WORLD.cx*view.scale;view.y=r.height/2-WORLD.cy*view.scale;view.ready=true;applyView();}
function zoomBy(f){const vp=$('participantNetwork');if(!vp)return;const r=vp.getBoundingClientRect(),mx=r.width/2,my=r.height/2,wx=(mx-view.x)/view.scale,wy=(my-view.y)/view.scale,next=clamp(view.scale*f,.55,1.9);view.x=mx-wx*next;view.y=my-wy*next;view.scale=next;applyView();}

function renderLegend(){const counts={covid:0,digital:0,wesad:0};CASES.forEach(c=>counts[c.study]++);$('networkLegend').innerHTML=Object.entries(STUDIES).map(([k,s])=>`<span class="study-chip ${k}"><i></i>${s.short} · ${counts[k]}</span>`).join('');}
function renderNetwork(list){
  const world=$('networkWorld');if(!world)return;
  const edges=list.map(c=>{const p=position(c),opacity=.14+(c.score/100)*.48,width=.8+(c.score-48)/49*2;return`<line class="network-edge ${c.study}" x1="${WORLD.cx}" y1="${WORLD.cy}" x2="${p.x.toFixed(1)}" y2="${p.y.toFixed(1)}" style="opacity:${opacity.toFixed(2)};stroke-width:${width.toFixed(2)}"></line>`;}).join('');
  const nodes=list.map(c=>{const p=position(c);return`<button class="network-node ${c.study}${c.id===selectedId?' selected':''}" data-case-id="${c.id}" type="button" style="left:${p.x}px;top:${p.y}px"><strong>${c.id}</strong><span>${c.score}% similarity</span></button>`;}).join('');
  world.innerHTML=`<svg class="network-lines" viewBox="0 0 ${WORLD.w} ${WORLD.h}" aria-hidden="true"><circle cx="${WORLD.cx}" cy="${WORLD.cy}" r="140"></circle><circle cx="${WORLD.cx}" cy="${WORLD.cy}" r="260"></circle><circle cx="${WORLD.cx}" cy="${WORLD.cy}" r="390"></circle>${edges}</svg><div class="you-node" style="left:${WORLD.cx}px;top:${WORLD.cy}px"><strong>YOU</strong><span>current pattern</span></div>${nodes}`;
  world.querySelectorAll('[data-case-id]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();selectedId=btn.dataset.caseId;render();}));
  if(!view.ready)requestAnimationFrame(resetView);else applyView();
}

function renderEvidence(c){
  const ev=c.evidence||{type:'events',title:'Reported timeline'};
  if(ev.type==='bars'){
    return `<div class="evidence-block"><div class="evidence-title">${ev.title}<span>reported in source study</span></div><div class="evidence-bars">${ev.rows.map((r,i)=>`<div class="evidence-row"><div><strong>${r.label}</strong>${r.note?`<small>${r.note}</small>`:''}</div><div class="evidence-track"><i style="--w:${Math.max(3,Math.min(100,r.value/r.max*100)).toFixed(1)}%;--delay:${i*80}ms"></i></div><b>${r.value}${r.suffix||''}</b></div>`).join('')}</div></div>`;
  }
  return `<div class="evidence-block"><div class="evidence-title">${ev.title}<span>select an event</span></div><div class="event-graph"><div class="event-line"></div>${c.timeline.map((t,i)=>`<button class="event-point${i===0?' active':''}" type="button" data-event-index="${i}" style="left:${c.timeline.length===1?50:(8+i*(84/(c.timeline.length-1)))}%"><i></i><span>${t[0]}</span></button>`).join('')}</div><div id="eventExplain" class="event-explain"><strong>${c.timeline[0][0]}</strong><span>${c.timeline[0][1]}</span></div></div>`;
}
function renderDetail(c,p){
  const s=STUDIES[c.study],host=$('simpleCaseDetail');
  const shared=c.signals.filter(x=>p.flags.includes(x));
  const sharedText=shared.length?shared.map(signalLabel).join(', '):'no currently flagged signal';
  const role=c.study==='wesad'?'This case is especially useful as a counterexample: a related wearable pattern occurred during experimentally induced stress rather than infection.':'This case is useful because the source study links a related wearable pattern to a documented clinical or inflammatory event.';
  host.innerHTML=`<div class="detail-head"><div><div class="eyebrow">Selected participant</div><h2>${c.id}</h2><span class="study-badge ${c.study}">${s.short}</span></div><div class="detail-score"><strong>${c.score}%</strong><span>PulseLab similarity</span></div></div><div class="detail-kind">${c.kind}</div><p class="detail-summary">${c.summary}</p><div class="detail-rationale"><strong>Why this participant is nearby</strong><p>Shared directional changes: ${sharedText}. ${role} The similarity percentage is a ranking aid, not a probability that you share the participant’s diagnosis.</p></div>${renderEvidence(c)}<div class="detail-outcome"><span>Reported outcome</span><strong>${c.outcome}</strong></div><div class="detail-timeline">${c.timeline.map((t,i)=>`<div><i>${i+1}</i><p><strong>${t[0]}</strong><span>${t[1]}</span></p></div>`).join('')}</div><div class="detail-source">Source: <a href="${s.url}" target="_blank" rel="noopener">${s.citation} ↗</a></div>`;
  host.querySelectorAll('[data-event-index]').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.eventIndex)||0;host.querySelectorAll('.event-point').forEach(x=>x.classList.toggle('active',x===btn));$('eventExplain').innerHTML=`<strong>${c.timeline[i][0]}</strong><span>${c.timeline[i][1]}</span>`;}));
}
function renderLibrary(){const counts={covid:0,digital:0,wesad:0};CASES.forEach(c=>counts[c.study]++);$('studyLibrary').innerHTML=Object.entries(STUDIES).map(([k,s])=>`<div class="study-library-item ${k}"><span>${counts[k]} participants shown</span><h3>${s.name}</h3><p>${k==='covid'?'Published COVID-19 cases with wearable warning signals and reported illness timelines.':k==='digital'?'Published infection and inflammation cases with reported wearable abnormalities and, in some participants, blood-test findings.':'Published stress-labeled recordings used as non-infection comparison cases.'}</p><a href="${s.url}" target="_blank" rel="noopener">Open source study ↗</a></div>`).join('');}

function render(){
  shell();const p=currentPattern(),list=ranked(p);if(!list.some(c=>c.id===selectedId))selectedId=list[0].id;const top=list[0],selected=list.find(c=>c.id===selectedId)||top,rec=recommendation(p,top);
  $('simpleTitle').textContent=rec.title;$('simpleBody').textContent=rec.body;$('simplePanel').textContent=rec.panel;$('simpleWindow').textContent=p.hasData?(rec.days<=3?'within 72 hours':`within ${rec.days} days`):'waiting for baseline';
  renderLegend();renderNetwork(list);renderDetail(selected,p);renderLibrary();if(p.hasData)publish(rec,top);
}
function schedule(){clearTimeout(timer);timer=setTimeout(render,100);}
document.addEventListener('input',schedule);document.addEventListener('change',schedule);window.addEventListener('pulselab:tab',e=>{if(e.detail?.tab==='population'){render();setTimeout(()=>{if(!view.ready)resetView();},40);}});render();
